import skipFormatting from "@vue/eslint-config-prettier/skip-formatting"
import { defineConfigWithVueTs, vueTsConfigs } from "@vue/eslint-config-typescript"
import pluginVue from "eslint-plugin-vue"

export default defineConfigWithVueTs(
  {
    name: "app/files-to-lint",
    files: ["**/*.{ts,mts,tsx,vue}"],
  },

  {
    name: "app/files-to-ignore",
    ignores: [
      "**/dist/**",
      "**/dist-ssr/**",
      "**/coverage/**",
      "**/node_modules/**",
      "src/api/schema.ts", // auto-generated by openapi-typescript
      "eslint.config.ts", // self-referential — lints its own file with no project context
    ],
  },

  pluginVue.configs["flat/recommended"],
  vueTsConfigs.recommendedTypeChecked,
  skipFormatting,

  {
    name: "app/unused-vars-underscore-pattern",
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
          destructuredArrayIgnorePattern: "^_",
          ignoreRestSiblings: true,
        },
      ],
    },
  },

  {
    // shadcn-vue ships single-word component names (Avatar, Button, etc.)
    // and exposes optional props without defaults; both are documented
    // conventions of the library and should not be linted against here.
    name: "app/shadcn-overrides",
    files: ["src/components/ui/**/*.vue"],
    rules: {
      "vue/multi-word-component-names": "off",
      "vue/require-default-prop": "off",
    },
  },
)
