import pluginVue from "eslint-plugin-vue"
import { defineConfigWithVueTs, vueTsConfigs } from "@vue/eslint-config-typescript"
import skipFormatting from "@vue/eslint-config-prettier/skip-formatting"

export default defineConfigWithVueTs(
  {
    name: "app/files-to-lint",
    files: ["**/*.{ts,mts,tsx,vue}"],
  },

  {
    name: "app/files-to-ignore",
    ignores: [
      "**/dist/**",
      "**/dist-ssr/**",
      "**/coverage/**",
      "**/node_modules/**",
      "src/api/schema.ts", // auto-generated by openapi-typescript
      "eslint.config.ts", // self-referential — lints its own file with no project context
    ],
  },

  pluginVue.configs["flat/recommended"],
  vueTsConfigs.recommendedTypeChecked,
  skipFormatting,
)
